libipt, ptunit: avoid lto maybe-uninitialized warning
Building with GCC 13 and -flto produces

    In function 'pt_qry_get_offset',
        inlined from 'get_offset_null' at .../libipt/test/src/ptunit-block_decoder.c:164:12,
        inlined from 'main' at .../libipt/test/src/ptunit-block_decoder.c:336:2:
    .../libipt/src/pt_query_decoder.c:380:16: error: 'decoder' may be used uninitialized [-Werror=maybe-uninitialized]
      380 |         return pt_evt_get_offset(&decoder->evdec, offset);
          |                ^
    .../libipt/src/pt_event_decoder.c: In function 'main':
    .../libipt/src/pt_event_decoder.c:1541:5: note: by argument 1 of type 'const struct pt_event_decoder *' to 'pt_evt_get_offset' declared here
     1541 | int pt_evt_get_offset(const struct pt_event_decoder *decoder, uint64_t *offset)
          |     ^
    .../libipt/test/src/ptunit-block_decoder.c:157:33: note: 'decoder' declared here
      157 |         struct pt_block_decoder decoder;
          |                                 ^

Those are false positive since the decoder object isn't actually used.  In

    &decoder->evdec

we compute the address of the event decoder object within the block
decoder object.  This adds an offset defined by the type.  It does not
actually dereference the pointer to access an uninitialized decoder
object.

Initialize the test decoder to avoid those warnings.  Fixes #101.

Signed-off-by: Markus Metzger <markus.t.metzger@intel.com>