test: Change it type to avoid implicit signedness conversion
Otherwise, clang with -Wsign-conversion complains about the assignment
to laddr here, because it is signed:

test/src/ptunit-image_section_cache.c:1597:27: error: implicit conversion changes signedness: 'int' to 'unsigned long long' [-Werror,-Wsign-conversion]
                laddr = 0x1000ull * (it % 23);
                                  ~  ~~~^~~~

Signed-off-by: Timm Bäder <tbaeder@redhat.com>